---
title: Pastor Jeremiah
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: contact@pastorjeremiah.com
buttondown: pastorjeremiah
description: 'Applying the Bible to your life in practical ways.

'
baseurl: 
url: https://pastorjeremiah.com
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
permalink: ":title/"
sass:
  style: compressed
  sass_dir: _sass
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENCE
- ".gitignore"
