# Site settings
title: "Pastor Jeremiah"
email: contact@pastorjeremiah.com
buttondown: pastorjeremiah
description: > # this means to ignore newlines until "baseurl:"
  Applying the Bible to your life in practical ways.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://pastorjeremiah.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
permalink: ":title/"

# Minification
sass:
  style: compressed
  sass_dir: _sass
  
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENCE
- .gitignore